import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/compoents/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <socials className="justify-center space-x-12 p-4  text-white flex flex-col md:flex-row
        bg-linear-to-t to-lime-400 from-lime-600">
          <div class="flex space-x-2">
            <a href="https://www.facebook.com/PandSContractingandLandscape/" target="_blank">FB</a>
            <a href="https://www.instagram.com/p.s.contracting/  " target="_blank">IG</a>
            <a href="https://www.bbb.org/us/pa/irwin/profile/landscape-contractors/ps-contracting-and-landscape-0141-71031381" target="_blank">BBB</a>
            <a href="index.html"></a>
            <a href="https://goo.gl/maps/SYQwxzQwuiNtmQCDA" target="_blank">Google</a>
          </div>
          <div>
            <p>(724) 382-8201</p>
          </div>
          <div>
            <p> pscontractingandLandscape@gmail.com</p>
          </div>
        </socials>
        <NavBar />
        {children}
        <footer className="bg-green-600 text-white text-center p-4">
          <p>&copy; {new Date().getFullYear()} P & S Contracting and Landscape. All rights reserved.</p>
          <p className="text-sm">
            Website by
            <a href="https://github.com/dmsacco" className="text-lime-400 hover:underline"> dmsacco</a>
          </p>
        </footer>
      </body>
    </html>
  );
}
